# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/umang/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="avit"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
# modify af-magic prompt
if [ $ZSH_THEME = "af-magic" ];
then
    PROMPT='$FG[105] ------------------------------------------------------------%{$reset_color%}
    $FG[032]%~\
    $(git_prompt_info) \
    $FG[105]%(!.#.»)%{$reset_color%} '
    ## color vars
    eval my_color='$FG[105]'

    # right prompt
    if type "virtualenv_prompt_info" > /dev/null
    then
    	RPROMPT='$(virtualenv_prompt_info)$my_color%n@%m%{$reset_color%}%'
    else
    	RPROMPT='$my_color%n@%m%{$reset_color%}%'
    fi
fi

# modify avit theme; this is more smart and pretty 
if [ $ZSH_THEME = "avit" ];
then 
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
    PROMPT='
$(_user_host)${_current_dir}
%{$fg[$CARETCOLOR]%}▶%{$resetcolor%} '  
    RPROMPT='%{$(echotc UP 1)%}$(virtualenv_prompt_info) $CONDA_DEFAULT_ENV $(_git_time_since_commit) $(git_prompt_status) $(git_prompt_info) ${_return_status}%{$(echotc DO 1)%}'
fi 

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
function add_path(){
    if [[ -d "$1" ]]; 
    then
        export PATH=$PATH:"$1"
    fi
}

export TERM=xterm-256color
alias juphub='jupyterhub --config ~/.jupyter/jupyterhub_config.py --port 20000'
alias a=clear
alias q=exit
alias sudo='sudo -E'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ipy=ipython3
alias py=python3

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

## anaconda
if [[ -f /home/umang/.anaconda/bin/activate ]] then 
    # anaconda adds ugly env name on each line, to feel anaconda we add and remove env name here
    function conda-activate(){
        PS1_backup=$PS1
        export PS1="$PS1 (${CONDA_DEFAULT_ENV})"
        source /home/umang/.anaconda/bin/activate
        export PS1="$PS1_backup"    
    }
    #alias conda-activate='source /home/umang/.anaconda/bin/activate'
    alias conda-deactivate='source /home/umang/.anaconda/bin/deactivate'
fi 

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

add_path "/snap/bin"
add_path "~/.local/bin"
add_path "~/bin" 

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Gurobi related
if [[ -d /opt/gurobi752/linux64 ]] then 
    export GUROBI_HOME=/opt/gurobi752/linux64
    export PATH=$PATH:$GUROBI_HOME/bin
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GUROBI_HOME/lib
    export GRB_LICENSE_FILE=/home/umang/.gurobi.license/gurobi.lic
fi
